version: '3.8'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    networks:
      - kafka-network  
    privileged: true

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    networks:
      - kafka-network  
    depends_on:
      - zookeeper
    restart: always 
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    privileged: true

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - kafka-network  
    environment:
      REDIS_PASSWORD: secret 
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "5540:5540"
    networks:
      - kafka-network   
    volumes:
      - redis-insight:/data  
    environment:
      - REDIS_PASSWORD=secret  

  nestjs-producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-producer  
    ports:
      - "3000:3000"
    networks:
      - kafka-network  
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    restart: always

volumes:
  redis-insight:

networks:
  kafka-network: 
    driver: bridge
